/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_PrincipalBanco;
import javax.swing.ButtonGroup;

/**
 *
 * @author Carlos
 */
public class FRM_PrincipalBanco extends javax.swing.JFrame {

    Controlador_FRM_PrincipalBanco controlador_FRM_PrincipalBanco;
    ButtonGroup botonesServicio= new ButtonGroup();
    ButtonGroup botonesPrioridad= new ButtonGroup();
    String abecedario[]= {"A","B","C","D","E","F","G","H","I","J","K","L","M","N","Ñ","O","P","Q","R","S","T","U","V","W","X","Y","Z"};
    private String servicio;
    private String prioridad;
    
    public FRM_PrincipalBanco() {
        super("Banco Estatal");
        initComponents();
        setLocationRelativeTo(this);
        controlador_FRM_PrincipalBanco= new Controlador_FRM_PrincipalBanco(this);
        agregarRadioBotones();
        agregarEventos();
        generarFicha();
    }
    
    public void agregarEventos() {
        this.btn_Generar.addActionListener(controlador_FRM_PrincipalBanco);
        this.btn_LLamar.addActionListener(controlador_FRM_PrincipalBanco);
        this.btn_Menor_Mayor.addActionListener(controlador_FRM_PrincipalBanco);
        this.btn_Mayor_Menor.addActionListener(controlador_FRM_PrincipalBanco);
        this.jrb_Cajas.addActionListener(controlador_FRM_PrincipalBanco);
        this.jrb_ServicioCliente.addActionListener(controlador_FRM_PrincipalBanco);
        this.jrb_Normal.addActionListener(controlador_FRM_PrincipalBanco);
        this.jrb_7600.addActionListener(controlador_FRM_PrincipalBanco);
    }
    public void agregarRadioBotones() {
        botonesServicio.add(jrb_Cajas);
        botonesServicio.add(jrb_ServicioCliente);
        botonesPrioridad.add(jrb_Normal);
        botonesPrioridad.add(jrb_7600);
    }
    public void resetearGUI() {
        this.jt_Nombre.setText("");
        this.jt_Edad.setText("");
    }
    public void resetearAtendiendo() {
        this.jta_Atendiendo.setText("");
    }
    public void definirServicio(String servicio) {
        this.servicio=servicio;
    }
    public void definirPrioridad(String prioridad) {
        this.prioridad=prioridad;
    }
    public void generarFicha() {
        
        this.jt_Ficha.setText("");
        int posLetra= (int) Math.round(Math.random()*26) ;
        int numAleatorio= (int) (Math.random()*(99-10+1)+10);
        this.jt_Ficha.setText(abecedario[posLetra]+numAleatorio);
    }
    public String[] devolverInformacion() {
        
        String arreglo[]= new String[5];
        
        arreglo[0]=this.jt_Ficha.getText();
        arreglo[1]=this.jt_Nombre.getText().trim();
        arreglo[2]=this.jt_Edad.getText().trim();
        arreglo[3]=this.servicio;
        arreglo[4]=this.prioridad;
        
        return arreglo;
    }
    public void mostrarLista(String lista) {
        
        this.jta_Lista.setText("");
        this.jta_Lista.setText(lista);
    }
    public void mostrarAtencionCliente(String atendiendo) {
        
        this.jta_Atendiendo.setText("");
        this.jta_Atendiendo.setText(atendiendo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j_Separador = new javax.swing.JSeparator();
        j_Separador2 = new javax.swing.JSeparator();
        jl_EntregaDeFichas = new javax.swing.JLabel();
        jl_Ficha = new javax.swing.JLabel();
        jl_Nombre = new javax.swing.JLabel();
        jl_Edad = new javax.swing.JLabel();
        jl_Servicio = new javax.swing.JLabel();
        jl_Prioridad = new javax.swing.JLabel();
        jt_Edad = new javax.swing.JTextField();
        jt_Ficha = new javax.swing.JTextField();
        jt_Nombre = new javax.swing.JTextField();
        jrb_Cajas = new javax.swing.JRadioButton();
        jrb_ServicioCliente = new javax.swing.JRadioButton();
        jrb_Normal = new javax.swing.JRadioButton();
        jrb_7600 = new javax.swing.JRadioButton();
        jl_LLamarClientes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_Atendiendo = new javax.swing.JTextArea();
        btn_Generar = new javax.swing.JButton();
        btn_LLamar = new javax.swing.JButton();
        btn_Menor_Mayor = new javax.swing.JButton();
        btn_Mayor_Menor = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jta_Lista = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        j_Separador.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jl_EntregaDeFichas.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_EntregaDeFichas.setText("Entrega de Fichas");

        jl_Ficha.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jl_Ficha.setText("Ficha:");

        jl_Nombre.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jl_Nombre.setText("Nombre:");

        jl_Edad.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jl_Edad.setText("Edad:");

        jl_Servicio.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jl_Servicio.setText("Tipo de Servicio:");

        jl_Prioridad.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jl_Prioridad.setText("Prioridad:");

        jt_Edad.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jt_Ficha.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jt_Ficha.setEnabled(false);

        jt_Nombre.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jrb_Cajas.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jrb_Cajas.setText("Cajas");

        jrb_ServicioCliente.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jrb_ServicioCliente.setText("Servicio al cliente");
        jrb_ServicioCliente.setActionCommand("ServicioCliente");

        jrb_Normal.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jrb_Normal.setText("Normal");

        jrb_7600.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jrb_7600.setText("7600");

        jl_LLamarClientes.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_LLamarClientes.setText("Llamar Clientes");

        jta_Atendiendo.setColumns(20);
        jta_Atendiendo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jta_Atendiendo.setRows(5);
        jta_Atendiendo.setEnabled(false);
        jScrollPane1.setViewportView(jta_Atendiendo);

        btn_Generar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_Generar.setText("Generar");

        btn_LLamar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_LLamar.setText("Llamar");

        btn_Menor_Mayor.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_Menor_Mayor.setText("<");

        btn_Mayor_Menor.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_Mayor_Menor.setText(">");

        jta_Lista.setColumns(20);
        jta_Lista.setRows(5);
        jta_Lista.setEnabled(false);
        jScrollPane2.setViewportView(jta_Lista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_Nombre)
                                    .addComponent(jl_Ficha)
                                    .addComponent(jl_Edad))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jt_Ficha, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jt_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jl_EntregaDeFichas)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_Servicio)
                                    .addComponent(jl_Prioridad))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrb_ServicioCliente)
                                    .addComponent(jrb_Cajas)
                                    .addComponent(jrb_Normal)
                                    .addComponent(jrb_7600)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btn_Generar)))
                .addGap(70, 70, 70)
                .addComponent(j_Separador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Menor_Mayor)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Mayor_Menor))
                            .addComponent(btn_LLamar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jl_LLamarClientes)
                                .addGap(106, 106, 106))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(j_Separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j_Separador)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jl_EntregaDeFichas)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Ficha)
                    .addComponent(jt_Ficha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Nombre)
                    .addComponent(jt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Edad)
                    .addComponent(jt_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Servicio)
                    .addComponent(jrb_Cajas))
                .addGap(18, 18, 18)
                .addComponent(jrb_ServicioCliente)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Prioridad)
                    .addComponent(jrb_Normal))
                .addGap(18, 18, 18)
                .addComponent(jrb_7600)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Generar)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jl_LLamarClientes)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_LLamar)
                .addGap(9, 9, 9)
                .addComponent(j_Separador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Menor_Mayor)
                    .addComponent(btn_Mayor_Menor))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_PrincipalBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_PrincipalBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_PrincipalBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_PrincipalBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_PrincipalBanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Generar;
    private javax.swing.JButton btn_LLamar;
    private javax.swing.JButton btn_Mayor_Menor;
    private javax.swing.JButton btn_Menor_Mayor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator j_Separador;
    private javax.swing.JSeparator j_Separador2;
    private javax.swing.JLabel jl_Edad;
    private javax.swing.JLabel jl_EntregaDeFichas;
    private javax.swing.JLabel jl_Ficha;
    private javax.swing.JLabel jl_LLamarClientes;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JLabel jl_Prioridad;
    private javax.swing.JLabel jl_Servicio;
    private javax.swing.JRadioButton jrb_7600;
    private javax.swing.JRadioButton jrb_Cajas;
    private javax.swing.JRadioButton jrb_Normal;
    private javax.swing.JRadioButton jrb_ServicioCliente;
    private javax.swing.JTextField jt_Edad;
    private javax.swing.JTextField jt_Ficha;
    private javax.swing.JTextField jt_Nombre;
    private javax.swing.JTextArea jta_Atendiendo;
    private javax.swing.JTextArea jta_Lista;
    // End of variables declaration//GEN-END:variables
}
